### ISSUE TITLE
I see an Error

### ISSUE THREAD

**Issue by VarunJoshihere** [rogersampaio/react-video-chapters#1]
It says ReactVideoChapters was not found in react-video-chapters

**Comment by rogersampaio** [comment]
Hi @VarunJoshihere , that's strange. I'll create a new React project and import it to try to reproduce the same error. Thanks for the feedback!

**Comment by rogersampaio** [comment]
Hi @VarunJoshihere , I updated the package.json and fixed the issue, please update to 1.0.2 version. Thanks for the feedback and sorry for the delay. I'm the only one working on this project. But it's open source, you would create a branch and fix the error yourself.

I hope this library is useful for you. I already had a lot of benefits from StackOverflow and Open Source community. This component was made with the intention to help others developers and not having to pay for a Video component that supports chapters and subtitles.
